name: nova_drawer
description: >-
  NovaDrawer – Production-grade Flutter drawer system with responsive layout
 

version: 1.2.0
homepage: https://github.com/yasersabri580-oss/NovaDrawer

environment:
  sdk: ^3.10.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  search_plus: ^3.2.3
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
