name: nova_drawer
description: >
  NovaDrawer – A modern, fully dynamic, and highly responsive
  app drawer component for Flutter supporting mobile, tablet, and desktop

version: 1.0.4
homepage: https://github.com/yasersabri580-oss/NovaDrawer

environment:
  sdk: ^3.10.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  search_plus: ^3.2.2
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
